// The idea bench: one rolling issue the nightly agent appends to, and the Monday brief harvests.
//
// Ideas are generated nightly and published weekly. That split is deliberate — nightly gives the
// agent many chances to notice something, weekly means the owner is shown at most three. Volume
// where it is free, restraint where attention is spent.

import { OWNER, REPO, gh, listOpenIssues, listComments, BENCH_TITLE, IDEA_MARKER } from "./github.mjs";

const BENCH_BODY = [
  "<!-- apm:system -->",
  "Ideas the nightly agent thought might suit this portfolio. **Nothing here is a commitment.**",
  "",
  "One rolling issue rather than an issue per idea — an idea nobody asked for should not cost a",
  "triage decision. The Monday brief surfaces at most three of the week's best; the rest sit here",
  "until you want them or they age out of relevance.",
  "",
  "**To promote one:** open a new issue (or use quick capture on the dashboard), paste the idea,",
  "and charter it like anything else. **To reject the whole line of thinking:** say so in a",
  "comment — the agent reads this issue before suggesting anything, so it will stop.",
  "",
  "Close this issue to turn idea generation off entirely."
].join("\n");

export async function findBench() {
  const issues = await listOpenIssues();
  return issues.find((i) => i.title === BENCH_TITLE) || null;
}

export async function ensureBench() {
  const existing = await findBench();
  if (existing) return existing;
  return gh(`/repos/${OWNER}/${REPO}/issues`, {
    method: "POST",
    body: JSON.stringify({ title: BENCH_TITLE, body: BENCH_BODY, labels: ["system"] })
  });
}

// Ideas already on the bench, newest first. The agent gets these so it does not re-suggest the
// same thing every night, and so the owner's rejections are visible to it.
export async function readBench({ days = 60, max = 40 } = {}) {
  const bench = await findBench();
  if (!bench) return { number: null, ideas: [], ownerNotes: [] };

  const comments = await listComments(bench.number);
  const cutoff = Date.now() - days * 86400000;
  const owner = OWNER.toLowerCase();

  const ideas = [];
  const ownerNotes = [];

  for (const c of comments) {
    const body = c.body || "";
    const isOwner = (c.user?.login || "").toLowerCase() === owner;

    if (isOwner) {
      // The owner talking back to the bench is a steer — keep it regardless of age.
      ownerNotes.push({ at: c.created_at, body: body.slice(0, 2000) });
      continue;
    }
    if (!body.includes(IDEA_MARKER)) continue;
    if (new Date(c.created_at).getTime() < cutoff) continue;

    // Titles are emitted as "### <title>" by postIdeas below.
    for (const m of body.matchAll(/^###\s+(.+)$/gm)) {
      ideas.push({ title: m[1].trim(), at: c.created_at });
    }
  }

  return {
    number: bench.number,
    url: bench.html_url,
    ideas: ideas.slice(-max),
    ownerNotes: ownerNotes.slice(-10)
  };
}

export async function postIdeas(ideas) {
  if (!Array.isArray(ideas) || !ideas.length) return null;

  const clean = ideas
    .filter((i) => i && typeof i.title === "string" && i.title.trim())
    .slice(0, 3)
    .map((i) => ({
      title: i.title.trim().slice(0, 200),
      why: String(i.why || "").trim().slice(0, 1200),
      fit: String(i.fit || "").trim().slice(0, 600)
    }));

  if (!clean.length) return null;

  const bench = await ensureBench();
  const date = new Date().toISOString().slice(0, 10);

  const body = [
    IDEA_MARKER,
    `**${date}**`,
    "",
    ...clean.flatMap((i) => [
      `### ${i.title}`,
      "",
      i.why,
      i.fit ? `\n*Why it fits you:* ${i.fit}` : "",
      ""
    ]),
    "<sub>Generated by nightly triage. Not a commitment and not a task — ignore freely.</sub>"
  ].join("\n");

  await gh(`/repos/${OWNER}/${REPO}/issues/${bench.number}/comments`, {
    method: "POST",
    body: JSON.stringify({ body })
  });

  return { number: bench.number, count: clean.length };
}
